#ifndef WLY_SANDBOX_ZHESHANLX_PROBLEM3_INCLUDE_ERRNO_H_
#define WLY_SANDBOX_ZHESHANLX_PROBLEM3_INCLUDE_ERRNO_H_

#define SUCCESS (0)
#define NULL_POINTER_ERROR (-1)
#define OPEN_FILE_ERROR (-2)
#define LINE_UNESCAPE_ERROR (-3)
#define EOF_ERROR (-4)
#define SEGMENTER_ERROR (-5)

#endif // WLY_SANDBOX_ZHESHANLX_PROBLEM3_INCLUDE_ERRNO_H_

